version: '3.8'

services:
  mediapipe-runner:
    build:
      context: ./mediapipe
    volumes:
      - /srv/docker/skelettschaetzer/data:/data
    container_name: mediapipe-container
    restart: "no"

  lightweight:
    build: ./lightweight
    volumes:
      - /srv/docker/skelettschaetzer/data:/data
    container_name: lightweight
    restart: "no"