version: '3.8'

services:

  input-loader:
    build: ./input-loader
    volumes:
      - /srv/docker/skelettschaetzer/data:/data
    restart: "no"

  blazepose:
    build: ./blazepose
    volumes:
      - /srv/docker/skelettschaetzer/data:/data
    container_name: blazepose
    restart: "no"
    depends_on:
      input-loader:
        condition: service_completed_successfully

  lightweight:
    build: ./lightweight
    volumes:
      - /srv/docker/skelettschaetzer/data:/data
    container_name: lightweight
    restart: "no"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    depends_on:
      input-loader:
        condition: service_completed_successfully

  densepose:
    build: ./densepose
    volumes:
      - /srv/docker/skelettschaetzer/data:/data
    container_name: densepose
    restart: "no"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    depends_on:
      input-loader:
        condition: service_completed_successfully

  tfpose:
    build: ./tfpose
    volumes:
      - /srv/docker/skelettschaetzer/data:/data
    container_name: tfpose
    restart: "no"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    depends_on:
      input-loader:
        condition: service_completed_successfully

  higher-hrnet:
    build: ./hrnet
    volumes:
      - /srv/docker/skelettschaetzer/data:/data
    restart: "no"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    depends_on:
      input-loader:
        condition: service_completed_successfully