version: '3.8'

x-gpu: &gpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

x-depends: &depends-on-video-loader
  depends_on:
    input-loader:
      condition: service_completed_successfully

x-volume: &input-volume
  volumes:
    - ${INPUT_FOLDER}:/data


services:

  # Vorbereitung
  input-loader:             # == Youtube-Downloader ==
    build: ./input-loader   # laedt ein YouTube-Video von einer gegebenen URL herunter,
    restart: "no"           # falls kein mp4-Video gegeben ist.
    <<: *input-volume       # Ausfuehrung vor den Skelettschaetzern.

  # Nachbereitung
  codecs:
    build: ./codecs
    restart: "no"
    <<: *input-volume
    depends_on:
      blazepose:
        condition: service_completed_successfully
      lightweight:
        condition: service_completed_successfully
      deeppose:
        condition: service_completed_successfully
      densepose:
        condition: service_completed_successfully
      tfpose:
        condition: service_completed_successfully
      higher-hrnet:
        condition: service_completed_successfully

  data-transformer:
    build: ./data_transformer
    restart: "no"
    depends_on:
      - codecs
    <<: *input-volume

  # Skelettschaetzer
  blazepose:
    build: ./pose/blazepose
    restart: "no"
    <<: [*depends-on-video-loader, *input-volume]

  lightweight:
    build: ./pose/lightweight
    restart: "no"
    <<: [*gpu, *depends-on-video-loader, *input-volume]

  densepose:
    build: ./pose/densepose
    restart: "no"
    <<: [*gpu, *depends-on-video-loader, *input-volume]

  tfpose:
    build: ./pose/tfpose
    restart: "no"
    <<: [*gpu, *depends-on-video-loader, *input-volume]

  higher-hrnet:
    build: ./pose/higher-hrnet
    restart: "no"
    <<: [*gpu, *depends-on-video-loader, *input-volume]

  deeppose:
    build:
      context: ./pose/mmpose
      args:
        POSE_CHECKPOINT_DOWNLOAD: https://download.openmmlab.com/mmpose/top_down/deeppose/deeppose_res152_coco_256x192-7df89a88_20210205.pth
    restart: "no"
    environment:
      OUTPUT_DIR: deeppose
      POSE_CONFIG: configs/body_2d_keypoint/topdown_regression/coco/td-reg_res152_8xb64-210e_coco-256x192.py
      POSE_CHECKPOINT: deeppose_res152_coco_256x192-7df89a88_20210205.pth
    <<: [*gpu, *depends-on-video-loader, *input-volume]

  cpm:
    build:
      context: ./pose/mmpose
      args:
        POSE_CHECKPOINT_DOWNLOAD: https://download.openmmlab.com/mmpose/v1/body_2d_keypoint/topdown_heatmap/coco/td-hm_cpm_8xb32-210e_coco-384x288-165487b8_20221011.pth
    restart: "no"
    environment:
      OUTPUT_DIR: cpm
      POSE_CONFIG: configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_cpm_8xb32-210e_coco-384x288.py
      POSE_CHECKPOINT: td-hm_cpm_8xb32-210e_coco-384x288-165487b8_20221011.pth
    <<: [*gpu, *depends-on-video-loader, *input-volume]
