version: '3.8'

x-gpu: &gpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]

x-depends: &depends-on-video-loader
  depends_on:
    input-loader:
      condition: service_completed_successfully

x-volume: &input-volume
  volumes:
    - ${INPUT_FOLDER}:/data


services:

  input-loader:             # == Youtube-Downloader ==
    build: ./input-loader   # laedt ein YouTube-Video von einer gegebenen URL herunter,
    restart: "no"           # falls kein mp4-Video gegeben ist.
    <<: *input-volume       # Ausfuehrung vor den Skelettschaetzern.

  blazepose:
    build: ./blazepose
    restart: "no"
    <<: [*depends-on-video-loader, *input-volume]

  lightweight:
    build: ./lightweight
    restart: "no"
    <<: [*gpu, *depends-on-video-loader, *input-volume]

  densepose:
    build: ./densepose
    restart: "no"
    <<: [*gpu, *depends-on-video-loader, *input-volume]

  tfpose:
    build: ./tfpose
    restart: "no"
    <<: [*gpu, *depends-on-video-loader, *input-volume]

  higher-hrnet:
    build: ./hrnet
    restart: "no"
    <<: [*gpu, *depends-on-video-loader, *input-volume]

  deeppose:
    build: ./deeppose
    restart: "no"
    <<: [*gpu, *depends-on-video-loader, *input-volume]