version: '3.8'

services:
  blazepose:
    build:
      context: ./blazepose
    volumes:
      - /srv/docker/skelettschaetzer/data:/data
    container_name: blazepose-container
    restart: "no"

  lightweight:
    build: ./lightweight
    volumes:
      - /srv/docker/skelettschaetzer/data:/data
    container_name: lightweight
    restart: "no"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

  hrnet:
    build: ./hrnet
    volumes:
      - /srv/docker/skelettschaetzer/data:/data
    container_name: hrnet
    restart: "no"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu