version: '3.8'

services:
  blazepose:
    build:
      context: ./blazepose
    volumes:
      - /srv/docker/skelettschaetzer/data:/data
    container_name: blazepose-container
    restart: "no"

  lightweight:
    build: ./lightweight
    volumes:
      - /srv/docker/skelettschaetzer/data:/data
    container_name: lightweight
    restart: "no"