version: '3.8'

services:
  blazepose:
    build: ./blazepose
    volumes:
      - /srv/docker/skelettschaetzer/data:/data
    container_name: blazepose
    restart: "no"

  lightweight:
    build: ./lightweight
    volumes:
      - /srv/docker/skelettschaetzer/data:/data
    container_name: lightweight
    restart: "no"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

  densepose:
    build: densepose
    volumes:
      - /srv/docker/skelettschaetzer/data:/data
    container_name: densepose
    restart: "no"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

  tfpose:
    build: tfpose
    volumes:
      - /srv/docker/skelettschaetzer/data:/data
    container_name: tfpose
    restart: "no"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu