# environment.yml
name: detectron
channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - python=3.8.1
  - pip
  - numpy
  - opencv
  - tensorboard
  - protobuf=3.17.2
  - pip:
      - onnx==1.11.0
      - torch==1.10
      - torchvision==0.11.1
      - git+https://github.com/facebookresearch/fvcore
