FROM python:3.11-slim


RUN apt-get update && apt-get install -y ffmpeg curl &&\
    rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir yt-dlp
WORKDIR /app
COPY exec.py .

# Standardbefehl: Hilfe anzeigen
CMD ["python", "exec.py"]
