# environment.yml
name: detectron
channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - python=3.8.1
  - pip
  - numpy
  - opencv
  - libstdcxx-ng
  - libgcc-ng
  - tensorboard
  - protobuf=3.17.2
  - scipy
  - pip:
      - torch==1.10.0+cu111
      - onnx==1.11.0
      - torchvision==0.11.1+cu111
      - torchaudio==0.10.0+cu111
      - fvcore @ git+https://github.com/facebookresearch/fvcore
      - rapidfuzz==1.9.1
      - av
      - -f https://download.pytorch.org/whl/cu111/torch_stable.html