name: hybrik
channels:
  - pytorch3d
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=11.3
  - fvcore
  - iopath
  - pip
  - ffmpeg
  - pip:
      - torch==1.12.1+cu113 
      - torchvision==0.13.1+cu113
      - -f https://download.pytorch.org/whl/torch_stable.html
